design : 온보딩 1단계 학과 선택 페이지의 리디자인
TeamDMU/DMU-Android pull request #137
Opened 2024-01-06 12:02 UTC by huiwoo-jo

## 📮 관련 이슈
- resolved 134

## ✍️ 구현 내용
- 온보딩 화면 1단계 학과 선택 페이지의 화면을 리디자인 하였습니다.
- 피그마 디자인에 맞춰 UI만 수정하였습니다.
- 제거 디자인 : 툴바
- 추가 디자인 : 설명, 진행표시줄, 검색창, 다음 버튼
- 추가 기능 : SpannableStringBuilder를 사용한 텍스트뷰 부분 색상 지정

![image](https://github.com/TeamDMU/DMU-Android/assets/84004687/192da811-efea-4004-b83a-f4cb1e90d304)

## ✔️ 확인 사항
- [x] 컨벤션에 맞는 PR 타이틀
- [x] 관련 이슈 연결
- [x] PR 관련 정보 연결 (작업자, 라벨, 마일스톤 등)
- [ ] Github Action 통과

2024-01-06 14:47 UTC, m6z1 reviewed
constraint layout 의 제약조건을 활용해서 xml 의 뎁스를 최대한 줄이면 좋을 것 같습니다!
그리고 `ctrl + alt + l` 로 포맷팅 하면 좋을 것 같고, 네이밍 (id 등등)은 일관적인 컨벤션을 따르면 좋을 것 같아서 리뷰에 남긴 PRND 컨벤션으로 통일하면 좋을 것 같습니다! (플젝 전체에 컨벤션)

2024-01-06 14:47 UTC, m6z1 commented on app/src/main/res/drawable-hdpi/bg_search_radius.xml
> +</shape>
당장 중요하진 않지만 저희 컨벤션도 한 번 정해보면 좋을 것 같아용
[PRND 컨벤션](https://github.com/PRNDcompany/android-style-guide/blob/main/Resource.md)

저는 애용합니다 .. PRND 컨벤션

2024-01-06 14:47 UTC, m6z1 commented on app/src/main/res/layout/activity_depart.xml
> +        </LinearLayout>
Constraint Layout 을 사용하고 있는데 Linear Layout은 사용하지 않아도 될 것 같습니다!
constraint layout 의 제약 조건으로 변경하면 좋을 것 같아요

2024-01-06 14:47 UTC, m6z1 commented on app/src/main/res/layout/activity_depart.xml
> +                android:text="소속 학과를 선택하면,"
text 값들은 string 추출 부탁드립니다 ~!

2024-01-06 14:47 UTC, m6z1 commented on app/src/main/res/layout/activity_depart.xml
> +                android:layout_marginVertical="8dp">
framelayout 을 사용하신 이유가 있을까요 ?!

2024-01-06 14:47 UTC, m6z1 commented on app/src/main/res/layout/activity_depart.xml
> +                android:backgroundTint="@color/gray300" />
단순히 검색 아이콘만 보이는 것이라면 ImageButton 은 사용할 필요가 없어보입니담

2024-01-06 14:47 UTC, m6z1 commented on app/src/main/res/layout/activity_depart.xml
> +                android:layout_height="30dp"
width 랑 height 의 값이 고정인 이유가 있나용 ?

2024-01-06 14:47 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartActivity.kt
> +
코드들 함수로 분리해주면 좋을 것 같습니다 !

2024-01-06 14:51 UTC, huiwoo-jo commented on app/src/main/res/drawable-hdpi/bg_search_radius.xml
> +</shape>
보내주신 컨벤션에 맞춰서 수정하겠습니다
노션에도 내용 추가하도록 하겠습니다!

2024-01-06 14:53 UTC, huiwoo-jo commented on app/src/main/res/layout/activity_depart.xml
> +        </LinearLayout>
두 라인의 글자 크기가 달라 작성하면서 편의를 위해 LinearLayout 묶었습니다.
각 view를 분리하여 Constraint로 묶을까요?

2024-01-06 14:58 UTC, huiwoo-jo commented on app/src/main/res/drawable/bg_circle.xml
> +</shape>
solid에 대한 정렬이시라면 shape에 속해있는 속성으로 이미 정렬이 되어있는 상태입니다!
color값을 지정하지 않을 경우에 view를 처음에 불러오게 되면 투명한 색으로 가져오게 됩니다
view의 색상을 지정하기 전 위치 확인을 위해 초기색으로 넣어봤는데 빼는게 나을까요?

2024-01-06 14:59 UTC, huiwoo-jo commented on app/src/main/res/layout/activity_depart.xml
> +                android:text="소속 학과를 선택하면,"
네 확인했습니다!
수정하겠습니다~!

2024-01-06 15:02 UTC, huiwoo-jo commented on app/src/main/res/layout/activity_depart.xml
> +                android:layout_marginVertical="8dp">
작성된 디자인에 맞춰서 구현하기 위해서 FrameLayout을 사용하였습니다
디자인에서 확인 하실 수 있듯 '바'와 '원'이 겹쳐져있습니다
비율에 맞춰 중첩을 표현하다보니 이렇게 구현하였는데 조율하여 수정이 필요해보입니다

2024-01-06 15:03 UTC, huiwoo-jo commented on app/src/main/res/layout/activity_depart.xml
> +                android:backgroundTint="@color/gray300" />
수정하겠습니다!

2024-01-06 15:04 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartActivity.kt
> +
함수로 분리하니 작동이 되지 않아 onCreate에 넣어뒀습니다..!
이 문제는 기능 부분을 수정, 구현하면서 확인할 필요가 있을거 같습니다

2024-01-06 15:10 UTC, huiwoo-jo commented on app/src/main/res/layout/activity_depart.xml
> +                android:layout_height="30dp"
통일성을 위하여 기존 프로젝트 내에 있는 검색창의 요소를 그대로 사용하였습니다
안드로이드 디자인 규격에 맞춰 28 혹은 36으로 수정할 필요가 있어보입니다

2024-01-06 15:14 UTC, m6z1 commented on app/src/main/res/drawable/bg_circle.xml
> +</shape>
재사용성을 위해서 저는 color 값을 안 두는 편이긴 합니다! xml에서도 색상을 추가할 수 있으니요 >.<

2024-01-06 15:17 UTC, huiwoo-jo commented on app/src/main/res/drawable/bg_circle.xml
> +</shape>
자주 사용하게 될 요소이니 안 넣는게 나을거 같긴하네요! 수정하도록 하겠습니다

2024-01-06 15:18 UTC, m6z1 commented on app/src/main/res/layout/activity_depart.xml
> +        </LinearLayout>
constraint layout 안에 linear layout 안에 textview 가 두 개 있으니, linear layout 을 빼고, constraint layout의 제약조건으로만 텍스트뷰 위치를 조정하면 좋을 것 같아요 ~! 뷰의 중첩은 최적화에 영향을 끼치니 불필요한 depth 는 줄이는 게 좋을 것 같습니다.

2024-01-06 15:21 UTC, huiwoo-jo commented on app/src/main/res/layout/activity_depart.xml
> +        </LinearLayout>
네 확인했습니다!!
TextView를 하나로 줄이고 SpannableStringBuilder으로 크기를 조절하는 방법도 있는데 이건 어떻게 생각하시나요?
이 경우에는 편의나 유지보수를 생각하면 TextView를 따로 두는게 나을거라고 생각하나 의견이 궁금합니다

2024-01-06 15:22 UTC, m6z1 commented on app/src/main/res/layout/activity_depart.xml
> +                android:layout_marginVertical="8dp">
framelayout 이 아니더라도 겹쳐서 보이게 뷰를 짤 수 있습니다! 한 번 도전해보시죠

2024-01-06 15:23 UTC, m6z1 commented on app/src/main/res/layout/activity_depart.xml
> +                android:layout_height="30dp"
요 아이콘 혹시 피그마에서 벡터 이미지로 추출해서 뽑으셨을까요 ?

2024-01-06 15:24 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartActivity.kt
> +
오잉 ? ? 몬가 이상한데 다시 확인해보시면 좋을 것 같아요

2024-01-06 15:24 UTC, huiwoo-jo commented on app/src/main/res/layout/activity_depart.xml
> +                android:layout_height="30dp"
아니요 검색창에 사용한 아이콘들은 기존 프로젝트에 있던 것을 사용했습니다

2024-01-06 15:29 UTC, huiwoo-jo commented on app/src/main/res/layout/activity_depart.xml
> +                android:layout_marginVertical="8dp">
다른 방법을 찾아서 수정해보도록 하겠습니다~!

2024-01-06 15:30 UTC, m6z1 commented on app/src/main/res/layout/activity_depart.xml
> +        </LinearLayout>
저는 TextView를 따로 만드는 방법을 선호하긴 합니다. xml 에서 view 두 개를 만들면 따로 유지 보수 할 수도 있기도 하고, 단순한 작업이니까요 !

2024-01-06 15:33 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartActivity.kt
> +
다시 확인하니 제대로 작동을하네요
아까는 kept 버전을 업데이트 하라는 오류가 떴었는데 일시적인 오류였나봅니다
다른 부분들을 수정하면서 같이 올리도록 하겠습니다!

2024-01-06 15:35 UTC, huiwoo-jo commented on app/src/main/res/layout/activity_depart.xml
> +        </LinearLayout>
혹시 몰라 다른 대안도 말씀드려봤습니당
Constraint 제약으로 수정하겠습니다!

2024-01-06 15:55 UTC, hoyahozz requested changes

2024-01-06 15:55 UTC, hoyahozz commented on app/src/main/res/layout/activity_depart.xml
> +                android:id="@+id/depart_spanText"
텍스트의 내용을 생각했을 때 이 ID명이 적합할까요?

2024-01-06 15:55 UTC, hoyahozz commented on app/src/main/res/layout/activity_depart.xml
> +            android:id="@+id/onboarding_progress"
`progress` 라는 이름이 `progressBar` 를 생각나게 해서 다른 네이밍을 고민해보는 것도 괜찮을 것 같아요~
`step` 이라는 이름은 어떨까요?

그리고 현재 XML의 다른 ID값과 비교했을 때 해당 ID명은 어떤 차이가 있을까요?

2024-01-06 15:55 UTC, hoyahozz commented on app/src/main/res/layout/activity_depart.xml
> +            android:layout_width="match_parent"
`ConstraintLayout` 을 사용할 때 `match_parent` 를 사용하는 것이 좋을까요?

2024-01-06 15:55 UTC, hoyahozz commented on app/src/main/res/values/dimens.xml
> -    <dimen name="font_size_24">20dp</dimen>
👍👍👍👍

2024-01-06 15:55 UTC, hoyahozz commented on app/src/main/res/layout/activity_depart.xml
>          </androidx.coordinatorlayout.widget.CoordinatorLayout>
`CoordinatorLayout` 는 스낵바가 올라올 때 리스트가 가려지는 버그를 막기 위해 추가된거라서

디자인처럼 `다음` 버튼이 추가될 계획이라면 제거해도 될 것 같아요~

2024-01-06 15:55 UTC, hoyahozz commented on app/src/main/res/layout/activity_depart.xml
> +            android:minHeight="56dp"
왜 `56dp` 인가요?

2024-01-06 15:56 UTC, huiwoo-jo commented on app/src/main/res/layout/activity_depart.xml
> +                android:id="@+id/depart_spanText"
SpannableStringBuilder를 사용하기 위한 id명으로 설정하였는데 텍스트 내용에 맞춰서 설정하는 편이 나은가요?

2024-01-06 15:58 UTC, huiwoo-jo commented on app/src/main/res/layout/activity_depart.xml
> +            android:id="@+id/onboarding_progress"
고민 후에 더 명확한 id로 수정하도록 하겠습니다!
다른 온보딩 화면들에서도 사용하기 위해서 depart가 이난 onboarding으로 아이디를 설정하였습니다

2024-01-06 16:01 UTC, huiwoo-jo commented on app/src/main/res/layout/activity_depart.xml
> +            android:layout_width="match_parent"
아 버릇처럼 match_parent를 자꾸 사용하네요.. 0dp로 수정하겠습니다~!

2024-01-06 16:01 UTC, hoyahozz commented on app/src/main/res/layout/activity_depart.xml
> +                android:id="@+id/depart_spanText"
id란 무엇일까요? 다른 텍스트뷰가 spanText 가 될 일은 없을까요?

2024-01-06 16:02 UTC, hoyahozz commented on app/src/main/res/layout/activity_depart.xml
> +            android:id="@+id/onboarding_progress"
다른 화면에서도 사용될 뷰라면 분리해보는건 어떨까요?

2024-01-06 16:03 UTC, huiwoo-jo commented on app/src/main/res/layout/activity_depart.xml
> +                android:id="@+id/depart_spanText"
현재 페이지 내에서 제한되게 생각한거 같습니다!
명확한 아이디로 수정하겠습니다

2024-01-06 16:04 UTC, huiwoo-jo commented on app/src/main/res/layout/activity_depart.xml
> +            android:id="@+id/onboarding_progress"
`progressbar`의 단계마다 원의 위치에 따른 색상과 텍스트가 달라지는데 뷰를 분리하면 이 부분을 어떻게 설정해야 할지 잘 모르겠습니다..!

2024-01-06 16:10 UTC, hoyahozz commented on app/src/main/res/layout/activity_depart.xml
> +            android:id="@+id/onboarding_progress"
커스텀뷰를 구현하는게 가장 좋고, 아니면 include 를 사용하는 것도 방법이겠네요!

2024-01-06 16:13 UTC, huiwoo-jo commented on app/src/main/res/layout/activity_depart.xml
> +            android:minHeight="56dp"
디자인으로 설정된 높이가 52dp였기에, 안드로이드 디자인 가이드의 56dp가 적합하다고 생각하여 설정하였습니다
검색과 취소 버튼이 있기에 넓은 시야를 확보와 검색 결과에 따른 `RecyclerView`의 `item`의 사이즈와 구분되면서, 현 페이지의 주요 기능인 검색을 눈에 띄게 만드는 사이즈라고 생각하였습니다

2024-01-06 16:17 UTC, huiwoo-jo commented on app/src/main/res/layout/activity_depart.xml
> +            android:id="@+id/onboarding_progress"
확인했습니다! 자료 조사 후 수정하도록 하겠습니다

2024-01-08 12:29 UTC, hoyahozz reviewed
많이 고쳐진 것 같아요~ 

이제 `activity_depart` 의 뷰 계층을 조금 더 `flat` 하게 수정해봅시다!

2024-01-08 12:29 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartActivity.kt
> +        spanText(binding.departTitleMain,0, 5)
시간이 꽤 흐른 후 코드를 다시 보았을 때 `0`, `5` 라는 숫자가 무엇을 뜻하는지 알 수 있을까요? 코틀린의 `named argument` 에 대해 공부해보면 좋을 것 같아요!

2024-01-08 12:29 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartActivity.kt
> +    private fun spanText(spanTextView: TextView, startIdx: Int, endEdx: Int){
함수명은 동사로 짓는 것이 이해가 더 쉬워요!

그리고 `endEdx` 는 무엇을 의미하나요? 줄임말도 좋지만, 명확하게 의미 표현이 어려울 때는 줄이지 않는 것도 방법입니다~

2024-01-08 12:29 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartActivity.kt
> -
설정 > 학과 선택 창에서는 좌측 상단에 `exit` 버튼이 필요하지 않을까요?

2024-01-08 12:29 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartActivity.kt
> +        spanTextView.text = ssb
```suggestion
        SpannableStringBuilder(binding.departSpanText.text).apply {
            setSpan(
                ForegroundColorSpan(getColor(R.color.main)),
                startIdex,
                endEdx,
                Spannable.SPAN_EXCLUSIVE_EXCLUSIVE
            )

            binding.departSpanText.text = this
        }
```

스코프 함수를 이용하면 조금 더 깔끔하게 구현할 수 있을 것 같아요~

2024-01-08 12:29 UTC, hoyahozz commented on app/src/main/res/layout/activity_depart.xml
> +            layout="@layout/layout_onboarding_step"
사람마다 조금 다를 수는 있겠지만, `include` 태그를 사용하더라도 해당 뷰는 `activity_depart` 에 속하게 되므로 이름 prefix 에는 `depart` 가 붙어야 된다고 생각해요~ 혹시 다른 의견이면 말씀해주세요!

2024-01-08 12:29 UTC, hoyahozz commented on app/src/main/res/layout/layout_onboarding_step.xml
> +            android:layout_marginEnd="24dp"
```suggestion
            android:layout_marginHorizontal="24dp"
            android:layout_marginTop="6dp"
```

2024-01-08 12:29 UTC, hoyahozz commented on app/src/main/res/layout/activity_depart.xml
> +            layout="@layout/layout_onboarding_step"
확실히 `include` 를 사용하니 코드가 더 깔끔해졌네요!

2024-01-08 12:29 UTC, hoyahozz commented on app/src/main/res/layout/layout_onboarding_step.xml
> +        <View
`ImageView` 가 아닌 `View` 를 사용한 이유가 있을까요? (궁금증)

2024-02-06 11:19 UTC, m6z1 requested changes
전체적으로 id 랑 resource 네이밍 컨벤션 prnd 로 맞춰주시고, 
피그마의 리디자인된 부분이랑 다른 것 같은데 디자인 의도하신 건지도 궁금합니다! 수고하셨어용

<img width="292" alt="스크린샷 2024-02-06 오후 8 19 28" src="https://github.com/TeamDMU/DMU-Android/assets/114990782/c167fbdb-d9e5-45c9-b361-0d92319568a6">

2024-02-06 11:19 UTC, m6z1 commented on app/src/main/res/drawable-hdpi/bg_search_white__radius_10dp.xml
> +<?xml version="1.0" encoding="utf-8"?>
이 코드 위치가 `drawable-hdpi` 에 있는데 의도하신 건가욥 ?

2024-02-06 11:19 UTC, m6z1 commented on app/src/main/res/drawable-hdpi/btn_gray_to_blue_10dp_enabled.xml
> +</selector>
이 코드두요 !

2024-02-06 11:19 UTC, m6z1 commented on app/src/main/res/layout/activity_depart.xml
> +                android:layout_width="match_parent"
```suggestion
                android:layout_width="0dp"
```
로 수정해주세염 !!

2024-02-06 11:19 UTC, m6z1 commented on app/src/main/res/layout/activity_depart.xml
> +                android:layout_width="match_parent"
```suggestion
                android:layout_width="0dp"
```
얘도 마찬가지로 !

2024-02-06 11:43 UTC, huiwoo-jo commented
> 전체적으로 id 랑 resource 네이밍 컨벤션 prnd 로 맞춰주시고, 피그마의 리디자인된 부분이랑 다른 것 같은데 디자인 의도하신 건지도 궁금합니다! 수고하셨어용
> 
> <img alt="스크린샷 2024-02-06 오후 8 19 28" width="292" src="https://private-user-images.githubusercontent.com/114990782/302604858-c167fbdb-d9e5-45c9-b361-0d92319568a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMTk5NzUsIm5iZiI6MTcwNzIxOTY3NSwicGF0aCI6Ii8xMTQ5OTA3ODIvMzAyNjA0ODU4LWMxNjdmYmRiLWQ5ZTUtNDVjOS1iMzYxLTBkOTIzMTk1NjhhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQxMTQxMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lN2RmOWUyYjc4ZmY2NTIzMzBhNDYzODI2MzNmOGY1OTRkYjRiZjdlZWI0YTIzMzJmMjQ4MTJkMWNlYTNhYzIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CpsEFCSm7A2NUdlxvxX3wIKSztN1i5_zCQaxrB5mKTQ">

내 컨벤션에 맞춰서 수정하도록 하겠습니다~ 검색창 하단 이후로의 학과 리스트는 디자인 뿐만 아니라 기능적인 부분이 얽혀있어서 기능 브랜치를 생성하여 수정이 필요해보입니다 컨벤션에 맞춰 수정 후 다시 알려드릴게용

2024-02-09 07:49 UTC, m6z1 requested changes
코멘트 확인 한 번 부탁드려요! ㅎㅎ 고생하셨습니다

2024-02-09 07:49 UTC, m6z1 commented on app/src/main/res/layout/layout_onboarding_step.xml
> +            android:id="@+id/onboarding_line"
```suggestion
            android:id="@+id/view_onboarding_line"
```
추가 부탁드립니다

2024-02-09 07:49 UTC, m6z1 commented on app/src/main/res/layout/layout_onboarding_step.xml
> +            android:id="@+id/onboarding_step_1"
```suggestion
            android:id="@+id/view_onboarding_step_1"
```
마찬가지입니다!

2024-02-09 07:49 UTC, m6z1 commented on app/src/main/res/layout/layout_onboarding_step.xml
> +            android:id="@+id/onboarding_step_3"
```suggestion
            android:id="@+id/view_onboarding_step_3"
```

2024-02-09 07:49 UTC, m6z1 commented on app/src/main/res/values/strings.xml
> +    <string name="depart_title_main">소속 학과를 선택하면,</string>
위 코드는 department인데 이 코드는 depart로 나눈 이유가 있으신가용?

2024-02-11 10:49 UTC, m6z1 approved these changes
고생만항써요 >.< merge it !!!

2024-02-13 03:59 UTC, hoyahozz approved these changes
고생하셨습니다! 👍👍👍👍👍

2024-02-14 22:28 UTC, merged