Design : 첨부파일 제외 상세보기 뷰 리디자인
TeamDMU/DMU-Android pull request #143
Opened 2024-02-02 16:09 UTC by m6z1

## 📮 관련 이슈
- resolved #142 

## ✍️ 구현 내용
- 리디자인한 상세보기 뷰 xml 작업

## 📷 구현 영상
<img width="355" alt="스크린샷 2024-02-03 오전 1 06 17" src="https://github.com/TeamDMU/DMU-Android/assets/114990782/e1813910-2f99-4223-89de-41d06527679d">

## ✔️ 확인 사항
- [ ] 컨벤션에 맞는 PR 타이틀
- [ ] 관련 이슈 연결
- [ ] PR 관련 정보 연결 (작업자, 라벨, 마일스톤 등)
- [ ] Github Action 통과

2024-02-03 12:32 UTC, hoyahozz requested changes

2024-02-03 12:32 UTC, hoyahozz commented on app/src/main/res/layout/activity_detail.xml
> +                android:hint="안녕하세ㅛ아아아ㅣㅣㄴㅇ럼ㄴ런"
```suggestion
                tools:hint="안녕하세ㅛ아아아ㅣㅣㄴㅇ럼ㄴ런"
```

2024-02-03 12:32 UTC, hoyahozz commented on app/src/main/res/layout/activity_detail.xml
> +                android:layout_width="wrap_content"
이거 작성자의 텍스트가 길어지면, 레이아웃에서 밀려날 것 같아요!

작성자, 구분선, 날짜가 모두 관계를 지니고 있도록 설정하시고, 여러 속성을 활용하면 어떠한 상황에서도 레이아웃을 온전히 보존할 수 있어요! 일종의 챌린지가 될 수도 있겠네요 😄

2024-02-03 12:32 UTC, hoyahozz commented on app/src/main/res/layout/activity_detail.xml
> +                android:hint="2024.02.01"
```suggestion
                tools:hint="2024.02.01"
```

2024-02-03 12:32 UTC, hoyahozz commented on app/src/main/res/layout/activity_detail.xml
> +                android:hint="손명지"
```suggestion
                tools:hint="손명지"
```

2024-02-03 12:32 UTC, hoyahozz commented on app/src/main/res/layout/activity_detail.xml
> +                        android:hint="반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반
```suggestion
                        tools:hint="반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ"
```

2024-02-03 12:32 UTC, hoyahozz commented on app/src/main/res/layout/activity_detail.xml
> +                        android:hint="반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반
디자인이 정상적으로 동작하는지 확인하는 경우엔 `Lorem Ipsum` 을 사용하는게 좀 더 깔끔할 것 같아요 😅

2024-02-03 12:32 UTC, hoyahozz commented on app/src/main/res/layout/activity_detail.xml
> +                    <androidx.constraintlayout.widget.ConstraintLayout
구조를 `flat` 하게 변경해주세요!

2024-02-03 12:36 UTC, m6z1 commented on app/src/main/res/layout/activity_detail.xml
> +                android:hint="안녕하세ㅛ아아아ㅣㅣㄴㅇ럼ㄴ런"
ㅠㅠ

2024-02-03 12:36 UTC, m6z1 commented on app/src/main/res/layout/activity_detail.xml
> +                android:hint="2024.02.01"
ㅠㅠ

2024-02-03 12:36 UTC, m6z1 commented on app/src/main/res/layout/activity_detail.xml
> +                android:hint="손명지"
ㅜㅠ

2024-02-03 12:37 UTC, m6z1 commented on app/src/main/res/layout/activity_detail.xml
> +                        android:hint="반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반갑스비나아럼ㄴ;렁;ㄹ넘라ㅣ;멀;ㅣㅁ너라ㅓㄴ맒ㄴ반갑습니다반
공부해보고 적용해보겠습니다🫡

2024-02-03 12:39 UTC, m6z1 commented on app/src/main/res/layout/activity_detail.xml
> +                    <androidx.constraintlayout.widget.ConstraintLayout
이 부분은 나중에 첨부파일의 유무에 따라 바인딩 어댑터로 레이아웃 전체를 visibility 처리를 하려고 했습니다. 구조를 flat 하게 바꾸는 게 나을까요? 🤔

2024-02-03 12:40 UTC, m6z1 commented on app/src/main/res/layout/activity_detail.xml
> +                android:layout_width="wrap_content"
도전해보겠습니다 ~.~

2024-02-03 12:41 UTC, hoyahozz commented on app/src/main/res/layout/activity_detail.xml
> +                    <androidx.constraintlayout.widget.ConstraintLayout
`ConstraintLayout` 의 `Group` 을 사용하면 뷰의 가시성을 한 번에 조정할 수 있어요!

2024-02-03 12:42 UTC, m6z1 commented on app/src/main/res/layout/activity_detail.xml
> +                    <androidx.constraintlayout.widget.ConstraintLayout
새로운 지식 습득 ~ 😋

2024-02-04 09:37 UTC, huiwoo-jo commented
수고하셨습니다!

2024-02-05 13:41 UTC, huiwoo-jo approved these changes
확인했습니다. 👍

2024-02-06 03:11 UTC, hoyahozz approved these changes
`tools:hint` 부분에 무의미한 문자열이 아닌 실제 학교 데이터를 넣으면 좀 더 이해가 쉬울 것 같아요! 이 부분만 수정 후 머지하셔도 될 것 같습니다! 고생하셨습니다 👍👍👍

2024-02-06 07:26 UTC, merged