Design : 검색 뷰 디자인
TeamDMU/DMU-Android pull request #148
Opened 2024-02-05 15:22 UTC by m6z1

## 📮 관련 이슈
- resolved #144 

## ✍️ 구현 내용
- 검색 뷰 디자인 구현 했습니다.
- 키보드가 올라왔을 때 바텀 네비게이션 보이지 않도록 구현했습니다.
- 검색 텍스트가 비어있는 게 아니거나 blank 가 아니라면 x 버튼인 텍스트 클리어 버튼이 뜨도록 구현했습니다.
- 현재 검색 텍스트의 `maxlength`는 10이지만, 추후에 수정될 수 있습니다.
- 검색 텍스트의 최소 length 인 2 일 때 디자인이 아직 나오지 않아 이 부분은 추후 반영하도록 하겠습니다. 
 
## 📷 구현
[Screen_recording_20240206_001658.webm](https://github.com/TeamDMU/DMU-Android/assets/114990782/a58ddc51-1182-42f2-85e6-c72fb74e9355)

## ✔️ 확인 사항
- [ ] 컨벤션에 맞는 PR 타이틀
- [ ] 관련 이슈 연결
- [ ] PR 관련 정보 연결 (작업자, 라벨, 마일스톤 등)
- [ ] Github Action 통과

2024-02-06 03:40 UTC, hoyahozz requested changes
코멘트 확인 부탁드립니다!

2024-02-06 03:40 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchViewModel.kt
> +    val searchClearVisibility: LiveData<Boolean> = _searchClearVisibility
`get() =` 과 `=` 는 어떤 차이가 있을까요?

2024-02-06 03:40 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
> +    }
`BaseFragment` 내에 있는 주석을 잘 살펴보고, 해당 메소드들이 어떤 메소드에 위치해야 하는지 파악하면 좋을 것 같아요!

2024-02-06 03:40 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
> +    }
이 메소드는 키보드 관련 유틸 함수로 분리할 수 있겠네요!

2024-02-06 03:40 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
> +        inputMethodManager.showSoftInput(binding.etSearchBar, InputMethodManager.SHOW_IMPLICIT)
이 부분도 키보드 관련 유틸 함수로 분리할 수 있습니다!

2024-02-06 03:40 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
> +        }
```suggestion
        binding.etSearchBar.requestFocus()
```

포커스만 줘도 키보드가 올라오지 않나요?

2024-02-06 03:40 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
> +        }
오히려 스코프 함수를 사용하지 않는게 코드 길이가 더 짧아질 것 같아요!

2024-02-06 03:40 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
> +            }
```suggestion
            override fun beforeTextChanged(s: CharSequence?, start: Int, count: Int, after: Int) = Unit

            override fun onTextChanged(s: CharSequence?, start: Int, before: Int, count: Int) = Unit
```

더 깔끔해보입니다!

2024-02-06 03:40 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchViewModel.kt
> +    private val _searchContent: MutableLiveData<String> = MutableLiveData()
내용은 언제 업데이트될까요?

2024-02-06 03:40 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchViewModel.kt
> +    }
```suggestion
    fun validateSearchClearButtonVisibility() {
        _searchClearVisibility.value = _searchContent.value.isNullOrEmpty().not()
    }
```

`not()` 을 사용하면 가독성이 좀 더 좋아져요!

2024-02-06 07:46 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
> +    }
이 부분에 대해서 궁금했는데, BaseFragment` `BaseActivity` `BaseViewModel` 을 사용했던 이유는 무엇이었나요 ??

2024-02-06 09:51 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
> +    }
공통 로직을 매번 정의하면 모든 화면이 코드가 길어지니, 이러한 코드를 줄이기 위해 사용했었어요!

다만 `BaseViewModel` 쪽은 저도 마음에 들지가 않아서.. 좀 수정이 필요할 것 같긴 하네요~

2024-02-06 11:47 UTC, huiwoo-jo approved these changes
정호님이 상세하게 리뷰해주셔서 제가 할게 없네용..
수고하셨습니다~!

2024-02-07 17:23 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchViewModel.kt
> +    val searchClearVisibility: LiveData<Boolean> = _searchClearVisibility
이 질문의 의도는 `get() = ` 사용과 `backing property` 의 차이점에 대해서 여쭤보시는 건가요 ?

2024-02-07 17:29 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
> +        }
```
binding.etSearchBar.post {
            binding.etSearchBar.setSelection(binding.etSearchBar.text.length)
        }
```

이 코드를 넣은 이유는 자동으로 텍스트의 길이에 맞춰 커서 위치를 끝으로 이동시키는 역할을 합니다. 

```
val searchKeyboard = binding.etSarchBar
```
는 제거해야겠군요 ㅎ,ㅎ

2024-02-07 17:32 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchViewModel.kt
> +    private val _searchContent: MutableLiveData<String> = MutableLiveData()
이 질문에 대한 의도를 이해하지 못했습니다 . . . .

2024-02-08 03:06 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchViewModel.kt
> +    val searchClearVisibility: LiveData<Boolean> = _searchClearVisibility
제가 말씀드린건 기본 `setter` 와 `property get` 의 차이입니다!

2024-02-08 03:12 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
> +        }
해당 함수는 `setupUI()` 에서 호출되고 있는데요, 최초 진입시엔 입력한 텍스트가 없지 않을까요? 😅

2024-02-08 03:21 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchViewModel.kt
> +    private val _searchContent: MutableLiveData<String> = MutableLiveData()
이번 로직에서는 `dataBinding` 을 사용하신 것 같은데요,

`searchContent` 의 값이 `XML`에서 업데이트되게 설정하였다면,

검색의 X 버튼도 `XML` 에서 업데이트되게 설정할 수 있지 않을까요?

지금은 `XML` 에서도 `ViewModel` 의 상태가 업데이트 되고 있고, 코틀린 코드에서도 상태가 업데이트 되고 있어요.
이렇게 상태 업데이트 로직이 여러 곳에 분산되어 있으면, 나중에 코드를 봤을 때 이해가 조금 어려울 것 같다는 생각이 듭니다!

2024-02-08 06:32 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
> +        }
아하.............!

2024-02-08 07:28 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchViewModel.kt
> +    private val _searchContent: MutableLiveData<String> = MutableLiveData()
`dataBinding` 로직을 삭제하고 코드 수정해서 푸쉬했습니다. 확인 부탁드려요 ☺️

2024-02-10 12:48 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchViewModel.kt
> +    val searchClearVisibility: LiveData<Boolean> = _searchClearVisibility
해결완료 ☺️

2024-02-11 05:23 UTC, hoyahozz approved these changes
고생하셨습니다 👍👍👍👍👍

2024-02-11 05:23 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
> +        }
`onClickListener` 를 한 번 더 분리해야 할까요?

2024-02-12 10:47 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
> +        }
onClickListener 메서드를 분리하지 않아도 된다는 말씀이신 건가요?

2024-02-13 03:59 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
> +        }
이 케이스를 따른다면 다른 `onClickListener` 를 구현할 때도 함수를 분리해야 하지 않을까요?

2024-02-13 13:14 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
> +        }
분리를 하는 게 맞다고 생각하는데 정호님께서는 `onClickListener` 메서드에서 모든 클릭 리스너 코드를 가지게 구현을 하실 것 같나요 /?

2024-02-13 23:43 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
> +        }
`setOnClickListener` 자체가 이미 함수로 분리되어 있기 때문에 분리할 필요까진 없다고 생각되는데요, 분리를 하는게 맞다고 생각하시는 이유가 궁금해요!

2024-02-15 11:46 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
> +        }
오호,,,, setonclicklostener가 함수라고 생각하지 못했어요 당연히 함수는 한 가지 일만 해야한다고 생각했고, 함수를 분리했을 때 가독성이 더 증가한다고 생각해서 분리했는데 클릭리수너 자체가 함수라곤 생각하지 못했네요,, 이 부분 코드 통일성 생각하며 희우님과도 얘기 나눠볼게요 감사함다

2024-02-15 11:52 UTC, merged