Design : 키워드 알림함 리디자인
TeamDMU/DMU-Android pull request #153
Opened 2024-02-08 08:29 UTC by m6z1

## 📮 관련 이슈
- resolved #145 

## ✍️ 구현 내용
- **툴바에 `action button` 추가했습니다. 키워드 알림함에서는 `편집` / 키워드 수정 뷰에서는 `완료` 로 사용될 예정입니다.**
- 키워드 알림함 리디자인 구현했습니다. 텍스트의 길이가 길어졌을 때 레이아웃에서 잘리지 않도록 노력했습니다 ^.^
- 데이터 바인딩을 삭제하면서 `알람 어댑터` 클래스를 **삭제** 했습니다. 추후 추가 예정입니다. 
- resource들 `prnd 컨벤션`에 맞게 수정했습니다. -> 다른 뷰는 추후 이슈파서 한 번에 적용하겠습니다.

## 📷 구현 영상
<img width="321" alt="스크린샷 2024-02-08 오후 5 28 52" src="https://github.com/TeamDMU/DMU-Android/assets/114990782/80f9402a-55e9-4711-a4df-a817370d9ef9">

## ✔️ 확인 사항
- [ ] 컨벤션에 맞는 PR 타이틀
- [ ] 관련 이슈 연결
- [ ] PR 관련 정보 연결 (작업자, 라벨, 마일스톤 등)
- [ ] Github Action 통과

2024-02-08 16:36 UTC, huiwoo-jo requested changes
저희의 id 컨벤션이 `<what>` 부분이 중점인거 같습니다!
앞으로의 지속적인 개발을 위하여 `<description>`도 구성하면 좋을거 같습니다.
참고를 위한 url 주소 남깁니다
https://kingji8life.tistory.com/224

전에 공유해주신 컨벤션 링크에서 `버튼기능을 위한 View는 ImageView, TextView로만 사용한다. (Button, ImageButton은 존재의 의미가 없음)` 부분이 있더라구요
ImageButton을 ImageView로만 사용할지 얘기해봐야할거 같습니당

2024-02-08 16:36 UTC, huiwoo-jo commented on app/src/main/res/layout/standard_toolbar.xml
> +            android:id="@+id/tv_toolbar_exit_button"
id에서 `_button` 보다는 `_btn`이 더 간결해서 선호하는데 어떻게 생각하시나요

2024-02-08 16:36 UTC, huiwoo-jo commented on app/src/main/res/layout/standard_toolbar.xml
> +            app:layout_constraintTop_toTopOf="@+id/tv_toolbar_exit_button" />
이것도 마찬가지로 `_btn`은 어떨까요?

2024-02-08 16:36 UTC, huiwoo-jo commented on app/src/main/res/layout/standard_toolbar.xml
> +            tools:hint="완료" />
학과 설정 파트를 위해 텍스트 색상 지정도 가능하면 좋을거 같아요!

2024-02-08 16:36 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/alarm/AlarmActivity.kt
>          }
`setupUI()`에서 `setupToolbar()`만 사용하는게 비효율적으로 보이는데 `setupUI()`에서 나중에 추가하실 부분이 있는건가요?

2024-02-09 07:31 UTC, m6z1 commented on app/src/main/res/layout/activity_alarm.xml
> -            app:title="@{@string/alarm_title}" />
데이터 바인딩을 지양하고 뷰 바인딩을 사용하기 위해서인데, 기술 스택 얘기를 같이 해보면 좋을 것 같아요 ~ 지금 툴바에 데이터 바인딩으로 로직이 짜여있어서 함께 사용하는 거다 보니 얘기를 하고 덜어내야 할 것 같아서요

2024-02-09 07:34 UTC, m6z1 commented on app/src/main/res/layout/standard_toolbar.xml
> +            android:id="@+id/tv_toolbar_exit_button"
[객체지향 생활 체조 원칙](https://suyeonchoi.tistory.com/m/69)](https://suyeonchoi.tistory.com/m/69)

에 의하면 줄여쓰지 않는 것이 원칙입니다. 물론, btn 같은 경우에는 통용되게 줄임말로 사용되고 있지만 코드의 일관성과 원칙을 따르기 위해 줄여쓰지 않았습니다. 이 부분은 통일하면 좋을 것 같습니다

2024-02-09 07:34 UTC, m6z1 commented on app/src/main/res/layout/standard_toolbar.xml
> +            app:layout_constraintTop_toTopOf="@+id/tv_toolbar_exit_button" />
위 회신 확인 부탁드립니다

2024-02-09 07:36 UTC, m6z1 commented on app/src/main/res/layout/standard_toolbar.xml
> +            tools:hint="완료" />
이 또한 기술 스택과 연관되는 부분인 것 같은데, 기술 스택 논의하면서 얘기해보면 좋을 것 같아요. 뷰바인딩을 사용한다면 xml에 로직을 둘 필요가 없어져서 지금은 넣지 않았습니다.

2024-02-09 07:37 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/alarm/AlarmActivity.kt
>          }
추가할 사항이 있어서 함수를 분리해서 넣어뒀는데, 이 부분은 남겨두지 않고 추후 추가할 때 분리하겠습니다 :)

2024-02-21 08:55 UTC, huiwoo-jo approved these changes
수고하셨습니당👍

2024-02-21 08:56 UTC, merged