Feat : 온보딩 3단계 키워드 알림 설정 페이지 구현
TeamDMU/DMU-Android pull request #155
Opened 2024-02-12 13:10 UTC by huiwoo-jo

## 📮 관련 이슈
- resolved #150 

## ✍️ 구현 내용
- 온보딩 3단계 키워드 알림 설정 페이지를 구현하였습니다.
- 온보딩 브랜치가 머지되지 않아 온보딩 2단계 구현 브랜치에서 중복되는 사항이 있습니다.
- 화면 상단에 화면 설명 부분을 추가하고 텍스트에 부분 색상을 설정하였습니다.
- 온보딩 단계에서 '알림 설정'이 활성화 됩니다.
- 키워드 알림설정 스위치 박스를 제작하였습니다.
- 스위치 박스 활성화에 따라 텍스트와 그림자의 색상이 변화합니다.
- 좌측의 leftDrawable의 색상은 아직 변화 방법을 찾지 못하였습니다. 의견이 있다면 말씀해주세요.
- 하단의 '알림 설정 및 시작하기'로 메인 화면으로 이동합니다.

## 📷 구현 영상
https://github.com/TeamDMU/DMU-Android/assets/84004687/01935845-172f-4529-af8d-456a676bf870

## ✔️ 확인 사항
- [x] 컨벤션에 맞는 PR 타이틀
- [x] 관련 이슈 연결
- [x] PR 관련 정보 연결 (작업자, 라벨, 마일스톤 등)
- [ ] Github Action 통과

2024-02-13 11:01 UTC, hoyahozz commented
이전 PR (#154)과 마찬가지로 베이스 브랜치를 변경하였습니다.

2024-02-13 11:12 UTC, hoyahozz requested changes
코멘트 확인 부탁드려요!

2024-02-13 11:12 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/settingAlarm/SettingAlarmActivity.kt
> +    @RequiresApi(Build.VERSION_CODES.P)
버전별 분기처리 하셔야합니다!

2024-02-13 11:12 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/settingAlarm/SettingAlarmActivity.kt
> +    override fun initDataBinding() {}
사용하지 않는다면 오버라이딩 하지 않으셔도 됩니다 :)

2024-02-13 11:12 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/settingAlarm/SettingAlarmActivity.kt
> +    }
공통 코드로 분리해주세요!

2024-02-13 11:12 UTC, hoyahozz commented on app/src/main/res/layout/activity_setting_alarm.xml
> +            app:layout_constraintStart_toStartOf="parent"
디바이스 크기가 작아지거나 가로 모드로 변경했을 때 다른 뷰가 가려지게 될 것 같아요! 한 번 확인 부탁드립니다!

2024-02-13 11:12 UTC, hoyahozz commented on app/src/main/res/layout/activity_setting_alarm.xml
> +                android:drawableLeft="@drawable/ic_alarm"
```suggestion
                android:drawableStart="@drawable/ic_alarm"
```

2024-02-13 14:47 UTC, m6z1 reviewed
`settingAlarm` 보다는 `permission` 이라는 네이밍이 더 맞지 않을까 싶은데 어떻게 생각하시나요 ?!
ㄴ 이유로는 1. 패키지명은 현재까지 모두 소문자로, 영단어 하나로만 이루어져있습니다.
2. 추후에 기능 추가 시 다른 권한이 필요할 때 이 부분에서 권한을 받게 될 것 같습니다.

2024-02-13 14:47 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/settingAlarm/SettingAlarmActivity.kt
> +    @RequiresApi(Build.VERSION_CODES.P)
제 플젝 중에 [슬슬](https://github.com/whatever-mentoring/SeulSeul_Android) 이라고 있는데 요기에 `notification` 권한 사용하고 있어서 보시면 도움 될 것 같아요!

2024-02-13 14:47 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/settingAlarm/SettingAlarmActivity.kt
> +    override fun initDataBinding() {}
오버라이딩 필수...라서 안 넣으면 빌드 에러나요 큼.....

2024-02-13 14:47 UTC, m6z1 commented on app/src/main/res/layout/activity_setting_alarm.xml
> +            android:id="@+id/tv_alarm_title_main"
alarm 이라는 액티비티가 따로 있어서 네이밍을 수정해야 할 것 같아요 !!

2024-02-13 14:47 UTC, m6z1 commented on app/src/main/res/layout/activity_setting_alarm.xml
> +            android:id="@+id/btn_alarm_complete"
`btn` 도 어떻게 해야할 지 논의 해봐야 할 것 같네용
네이밍으로든, 뷰 사용법이든 !

2024-02-13 14:50 UTC, m6z1 reviewed
`settingAlarm` 보다는 `permission` 이라는 네이밍이 더 맞지 않을까 싶은데 어떻게 생각하시나요 ?!
ㄴ 이유로는 1. 패키지명은 현재까지 모두 소문자로, 영단어 하나로만 이루어져있습니다.
2. 추후에 기능 추가 시 다른 권한이 필요할 때 이 부분에서 권한을 받게 될 것 같습니다.

2024-02-13 23:44 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/settingAlarm/SettingAlarmActivity.kt
> +    override fun initDataBinding() {}
앗 맞네요 ㅎㅎ..

```suggestion
    override fun initDataBinding() = Unit
```

으로 변경해주시면 될 것 같습니다!

2024-02-22 11:50 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/settingAlarm/SettingAlarmActivity.kt
> +    @RequiresApi(Build.VERSION_CODES.P)
모르고있었던 부분이었어요! 하나 알아갑니다

2024-03-05 11:04 UTC, m6z1 requested changes
고생하셨어요! 코멘트 확인 부탁드립니다 :)

2024-03-05 11:04 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/standard/base/BaseActivity.kt
> +    protected fun setSpanText(spanTextView: TextView, startIdx: Int, endIdx: Int){
확장함수로 빼면 어떨까요유

2024-03-05 11:04 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/KeywordActivity.kt
>                  startActivity(intent)
observe 한 뒤에 액티비티까지 넘기는 로직은 분리하는 게 어떨까요 ?

2024-03-05 11:04 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/permission/OnboardingPermission.kt
> +        binding.vm = viewModel
데이터 바인딩 사용하고 있는 부분 액티비티에서 진행하면 어떨까요?

2024-03-05 11:04 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/permission/OnboardingPermission.kt
> +class OnboardingPermission : BaseActivity<ActivityOnboardingPermissionBinding, SettingViewModel>() {
클래스명 뒤에 Activity 붙이지 않은 이유가 있을까요 ?

2024-03-05 11:04 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/permission/OnboardingPermission.kt
> +
의미없는 줄 공백은 지워도 될 것 같습니다

2024-03-05 11:04 UTC, m6z1 commented on app/src/main/res/layout/activity_onboarding_permission.xml
> +            app:layout_constraintTop_toTopOf="parent" />
color 값이 없네요

2024-03-05 11:04 UTC, m6z1 commented on app/src/main/res/layout/activity_onboarding_permission.xml
> +            app:layout_constraintTop_toTopOf="@id/tv_permission_title_main" />
여기도 컬러값이 없어요!!

2024-03-06 01:43 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/standard/base/BaseActivity.kt
> +    protected fun setSpanText(spanTextView: TextView, startIdx: Int, endIdx: Int){
확장함수로 뺐다가 `Base Activity`로 뺏는데 어제 말씀드린거처럼 추후에 확장성을 생각하면 나중에 확장함수로 빼는게 좋을거 같습니다! 현재 세개의 뷰에 얽혀있어서 한 번에 하는게 나을거 같아요

2024-03-06 01:43 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/permission/OnboardingPermission.kt
> +        binding.vm = viewModel
수정하겠습니다!

2024-03-06 01:43 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/permission/OnboardingPermission.kt
> +class OnboardingPermission : BaseActivity<ActivityOnboardingPermissionBinding, SettingViewModel>() {
실수로 빠졌네요 수정하겠습니다!

2024-03-06 01:44 UTC, huiwoo-jo commented on app/src/main/res/layout/activity_onboarding_permission.xml
> +            app:layout_constraintTop_toTopOf="parent" />
컬러값을 지정 안해도 자동으로 `black` 지정이 되어서 자꾸 까먹네요😅
앞으로 더 신경쓰겠습니다

2024-03-12 11:33 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/KeywordActivity.kt
>                  startActivity(intent)
이건 키워드 액티비티 부분으로 따로 브랜치를 파서 작업하는게 좋을거 같습니다

2024-03-12 11:55 UTC, closed without merging