Feature : 설정 화면 내 학과 선택
TeamDMU/DMU-Android pull request #161
Opened 2024-02-20 14:02 UTC by huiwoo-jo

## 📮 관련 이슈
- resolved #160

## ✍️ 구현 내용
- 설정 화면에서 사용할 학과 선택 화면을 구현하였습니다.
- 온보딩 학과 선택과 화면을 분리 하되 viewModel과 Adapter는 공통으로 사용하였습니다.
- 뒤로가기를 누를 경우 학과는 변경되지 않습니다.

- 완료, 뒤로 가기 선택 시 메인 화면으로 이동하지만, 설정 화면으로 이동이 사용자가 편리할 것으로 생각해 의논할 필요성이 있습니다.
- 변경 전 기존 설정한 학과가 선택되어 있는 것이 사용자 편의성이 좋을듯하여 논의가 필요합니다.

## 📷 구현 영상
|https://github.com/TeamDMU/DMU-Android/assets/84004687/74222b06-e395-4505-a38a-7234db3f844b|![image](https://github.com/TeamDMU/DMU-Android/assets/84004687/93c437de-055e-46d2-b189-35c31165d9de)|
|---|---|

## ✔️ 확인 사항
- [x] 컨벤션에 맞는 PR 타이틀
- [x] 관련 이슈 연결
- [x] PR 관련 정보 연결 (작업자, 라벨, 마일스톤 등)
- [ ] Github Action 통과

2024-02-21 07:29 UTC, m6z1 requested changes
고생많았어요 >,,< 코멘트 확인 부탁드려영

2024-02-21 07:29 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartActivity.kt
> +    lateinit var adapter: DepartAdapter
`adapter` 가 public 한 이유가 무엇인가요 ?

2024-02-21 07:29 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartActivity.kt
> +    }
사용하지 않는 함수는 
```suggestion
    override fun initDataBinding() = Unit
```
으로 정리해주시면 좋을 것 같아요 << 정호씨가 알려줌

2024-02-21 07:29 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartActivity.kt
> +            if (it != -1) getDepart(items)
-1이 어떤 수인가요 ?

2024-02-21 07:29 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/OnboardingDepartActivity.kt
> +    lateinit var adapter: DepartAdapter
얘도 `adapter`가 public 해야 할까요 ?

2024-02-21 07:29 UTC, m6z1 commented on app/src/main/res/layout/activity_onboarding_depart.xml
> +            app:layout_constraintTop_toTopOf="parent" />
color 값이 없네요!

2024-02-21 07:29 UTC, m6z1 commented on app/src/main/res/layout/activity_onboarding_depart.xml
> +            app:layout_constraintTop_toTopOf="@id/tv_onboarding_depart_title_main" />
얘도 컬러값없어용

2024-02-21 07:29 UTC, m6z1 commented on app/src/main/res/layout/activity_onboarding_depart.xml
> +                android:background="@android:color/transparent"
```suggestion
                android:background="@null"
```
을 사용하면 밑줄을 제거할 수 있어용

2024-02-21 07:29 UTC, m6z1 commented on app/src/main/res/layout/activity_onboarding_depart.xml
> +                android:hint="@string/department_search_message"
hint color 값은 따로 없었나용 ?

2024-02-21 07:29 UTC, m6z1 commented on app/src/main/res/layout/activity_onboarding_depart.xml
> +            <EditText
`maxLines` 추가해주세욥

2024-02-21 07:29 UTC, m6z1 commented on app/src/main/res/layout/activity_onboarding_depart.xml
> +
한 줄로 수정부탁드려요!

2024-02-21 07:29 UTC, m6z1 commented on app/src/main/res/layout/activity_onboarding_depart.xml
> +
두 줄!

2024-02-29 01:12 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartActivity.kt
> +    lateinit var adapter: DepartAdapter
앗 아니용 `private` 처리를 까먹었네요! 수정하겠습니다

2024-02-29 01:12 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/OnboardingDepartActivity.kt
> +    lateinit var adapter: DepartAdapter
얘도 수정하겠습니다~!

2024-02-29 01:15 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartActivity.kt
> +            if (it != -1) getDepart(items)
학과 리스트의 인덱스 값을 나타내는 것으로 -1은 일치하는 값이 없을 경우 리턴되는 것으로 알고 있습니당

2024-02-29 01:19 UTC, huiwoo-jo commented on app/src/main/res/layout/activity_onboarding_depart.xml
> +                android:background="@android:color/transparent"
오 배워갑니다 👍

2024-02-29 01:20 UTC, huiwoo-jo commented on app/src/main/res/layout/activity_onboarding_depart.xml
> +                android:hint="@string/department_search_message"
확인해보니 `gray300`으로 설정되어있네요 수정하겠습니다!

2024-02-29 12:12 UTC, m6z1 approved these changes
고생하셨어요 !!

2024-02-29 12:12 UTC, m6z1 commented on app/src/main/res/layout/activity_depart.xml
> +            app:title="@{@string/department_title}" />
데바 지우고 뷰바인딩 사용해보시죠 !

2024-03-02 04:44 UTC, huiwoo-jo commented on app/src/main/res/layout/activity_depart.xml
> +            app:title="@{@string/department_title}" />
이 부분도 바꾸려고 했는데 `include`로 잡혀있는 코드여서 그런지 안 바뀌더라구요..😅

2024-03-06 03:48 UTC, merged