Feat : 대학/학과 공지 뷰 api 연결 및 무한 스크롤 적용
TeamDMU/DMU-Android pull request #167
Opened 2024-02-23 13:07 UTC by m6z1

## 📮 관련 이슈
- resolved #164 

## ✍️ 구현 내용
- 대학/학과 공지 api 연결했습니다.
- 각 공지에 무한 스크롤 적용했습니다. (로딩 뷰 적용)
- 캐싱 작업은 앱이 실행되어 있는 동안 적용 되어있습니다. > 추후 수정해보겠습니다.
- `데이터 바인딩`을 제거하고 `뷰바인딩` 적용했습니다. 

## 📷 구현 영상
- 
[Screen_recording_20240223_220356.webm](https://github.com/TeamDMU/DMU-Android/assets/114990782/a97f8d3a-f1a7-4867-b62d-bf362636253a)

## ✔️ 확인 사항
- [ ] 컨벤션에 맞는 PR 타이틀
- [ ] 관련 이슈 연결
- [ ] PR 관련 정보 연결 (작업자, 라벨, 마일스톤 등)
- [ ] Github Action 통과

2024-02-23 18:30 UTC, huiwoo-jo requested changes
관련 지식이 모자라서 적극적인 리뷰가 어려운 점 양해부탁드립니다ㅠㅠ
전체적인 코드 정렬과 id 컨벤션 수정 정도면 될거 같아용
코멘트 확인 부탁드립니다!

2024-02-23 18:30 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/data/repository/NoticeRepository.kt
> -    fun getDepartmentCode(): Int = SharedPreference.getCode()
fetchSearchNotices는 검색 파트에서 필요할거 같은데 이건 따로 구현하실 예정인가요?

2024-02-23 18:30 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/standard/network/RetrofitObject.kt
> +        val baseUrl = "https://triphub.kr/"
나중에 baseUrl 숨김 처리 하는걸 같이 고민하면 좋을거 같아요!
제가 해봤는데 실패해서.. 나중에 정보 공유가 필요할거 같습니다

2024-02-23 18:30 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeFragment.kt
> -        // 새로고침 했을 때 동작
주석이 있는편이 나중에 확인하기 편할거 같은데 개발 과정에서 지우신건가용

2024-02-23 18:30 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeFragment.kt
> -        LocalBroadcastManager.getInstance(requireContext()).unregisterReceiver(localBroadCast)
단순 궁금증 : 이 파트가 왜 지워진건지 궁금합니당

2024-02-23 18:30 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeFragment.kt
> +                            NoticeTabType.SCHOOL -> viewModel.fetchUniversityNotices()
NoticeTabType이 FACULTY와 SCHOOL을 사용하면 통일성이 떨어질거 같은데 이유가 있을까요?

2024-02-23 18:30 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeViewModel.kt
> +                noticeRepository.fetchDepartmentNotices("컴퓨터소프트웨어공학과", departmentNoticeCurrentPage)) {
인자 줄바꿈이 필요할거 같네요
`ctrl + alt + l`로 정리 부탁드려요!

2024-02-23 18:30 UTC, huiwoo-jo commented on app/src/main/res/layout/item_notice.xml
>              android:id="@+id/item_notice_title"
id 컨벤션에 맞춰서 수정해야할거 같습니당

2024-02-23 18:30 UTC, huiwoo-jo commented on app/src/main/res/values/strings.xml
> +    <string name="notice_tab_faculty">학과 공지</string>
학과 `string`을 `department`를 사용하는데 `faculty`를 사용하면 통일성이 떨어질거 같습니다!
충돌을 피하려고 바꾸시지 않은걸까요?

2024-02-24 02:15 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/data/repository/NoticeRepository.kt
> -    fun getDepartmentCode(): Int = SharedPreference.getCode()
넵 추후 따로 구현할 예정입니다

2024-02-24 02:16 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeFragment.kt
> -        // 새로고침 했을 때 동작
넴 메서드명이 직관적이라면 주석은 불필요하다 생각해서 주석은 다 제거했습니다

2024-02-24 02:19 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeFragment.kt
> -        LocalBroadcastManager.getInstance(requireContext()).unregisterReceiver(localBroadCast)
Fcm 관련 코드인 것 같아서 지웠는데 fcm 제가 구현해보고 싶어서요 ㅎㅅㅎ

2024-02-24 02:20 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeFragment.kt
> +                            NoticeTabType.SCHOOL -> viewModel.fetchUniversityNotices()
서버 API와 통일 성을 맞추기 위해서 
FACULTY -> Department
SCHOOL -> University
로 수정했습니다.

2024-02-24 02:28 UTC, m6z1 commented on app/src/main/res/values/strings.xml
> +    <string name="notice_tab_faculty">학과 공지</string>
오 아뇨 학과곹지로만 수정한다고 못 봤습니다 꼼꼼하시군요

2024-02-25 02:10 UTC, huiwoo-jo approved these changes

2024-02-25 02:11 UTC, huiwoo-jo approved these changes
수고하셨어요~!👍

2024-02-25 06:17 UTC, merged

2024-02-28 03:04 UTC, hoyahozz reviewed
중요한 부분이라 늦었지만 리뷰 남겨봅니다.

1. 다크모드 혹은 가로모드 변경으로 구성 변경을 발생시킨 후 페이징이 정상적으로 작동하는지 테스트 해보아요 :)
2. 일반적으로 페이징의 경우 전체 로딩을 띄우기 보단 리스트 마지막에 로딩을 띄우는 경우가 많습니다! 이 부분 도전해보시면 어떨까요?

2024-02-28 03:04 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeViewModel.kt
> +                        "컴퓨터소프트웨어공학과", DEFAULT_REFRESH_PAGE
임시 코드일까요?

2024-02-28 09:52 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/notice/NoticeViewModel.kt
> +                        "컴퓨터소프트웨어공학과", DEFAULT_REFRESH_PAGE
네 아직 학과 설정 부분 연결이 되지 않아서 추후에 수정할 예정입니다