Feat : 학사 일정 api 수정
TeamDMU/DMU-Android pull request #172
Opened 2024-02-24 12:55 UTC by huiwoo-jo

## 📮 관련 이슈
- resolved #151
- resolved #171

## ✍️ 구현 내용
- 학사 화면 api를 수정하였습니다.
- 데이터 구조로 인하여 함수와 데이터 클래스가 복잡해졌습니다.
- 기존 구조 문제로 하지 못한 리디자인도 같이 하였습니다.
- 학사 일정 최소 수치는 2024.01.01 ~ 2025.02.28 로 수정하였으나 지속적인 관리를 위하여 데이터로 수정하는 것이 좋을 수도 있을거 같습니다. local date를 사용하는 것이 오히려 부담이 될 수도 있을거 같아 논의가 필요합니다.

## 📷 구현 영상
|https://github.com/TeamDMU/DMU-Android/assets/84004687/9ee27d50-b16a-403c-b712-bea1bd5b2b88|![image](https://github.com/TeamDMU/DMU-Android/assets/84004687/b39ebadf-805e-48e3-a46a-140fa41ab57f)|
|---|---|

## ✔️ 확인 사항
- [x] 컨벤션에 맞는 PR 타이틀
- [x] 관련 이슈 연결
- [x] PR 관련 정보 연결 (작업자, 라벨, 마일스톤 등)
- [ ] Github Action 통과

2024-02-24 13:56 UTC, m6z1 requested changes
고생많았어요 !! 코멘트 확인 부탁드립니다아

2024-02-24 13:56 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/data/remote/service/CafeteriaService.kt
> +    @GET("/api/v1/dmu/diet")
앞에 슬래쉬 빼주세영

2024-02-24 13:56 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/adapter/ScheduleAdapter.kt
>      }
`inner class` 에 관해서 정리된 아티클인데 한 번 읽어보시면 좋을 것 같아요
[블로그 링크](https://thdev.tech/kotlin/2020/11/17/kotlin_effective_11/)

2024-02-24 13:56 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/cafeteria/CafeteriaFragment.kt
> +            stuKoreanMenuAdapter.submitList(it)
`stu`가 어떤 것의 약자인가요 ? 최대한 줄여쓰는 것을 지양하면 좋을 것 같습니다!

2024-02-24 13:56 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/ScheduleFragment.kt
>          binding.vm = viewModel
데이터 바인딩을 지워보아요

2024-02-24 13:56 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/ScheduleFragment.kt
>                  .commit()
요 부분 회의 때 의논해보면 좋을 것 같은데, 아마 `dmforu` 를 사용하고 있는 학생은 재학생일 것 같아서 -1년까지는 추가하면 어떨까 싶어요. 작년 학사일정도 확인할 수 있는 게 장점이지 않을까 싶네용

2024-02-24 13:56 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/ScheduleViewModel.kt
> +        Log.d("scheTest", "대기")
로그 지워주세영

2024-02-24 13:56 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/ScheduleViewModel.kt
> +                        Log.d("scheTest", "실패")
로그 지워주세영

2024-02-24 13:56 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/ScheduleViewModel.kt
> +
값을 필터링하는 부분이 알아보기 조금 어려운 것 같아요 🤔 추후에 다른 코드로 리팩토링해주실 수 있나영

2024-02-24 13:56 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/ScheduleViewModel.kt
> +                    }?.scheduleEntries.orEmpty()
이 코드가 아까 선택한 연월일에 따라 필터링하는 코드와 로직이 같은 것 같은데 로직이 같다면 함수로 분리해서 사용해도 되지 않을까요 ?

2024-02-24 13:56 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/adapter/ScheduleAdapter.kt
> +        fun bind(item: ScheduleEntry) {
함수 개행 해주세염

2024-02-24 13:56 UTC, m6z1 commented on app/src/main/res/layout/item_schedule.xml
>      </data>
데이터 바인딩을 사용하는 로직이 없는 것 같은데 제거해도 되지 않을까욥?

2024-02-24 16:40 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/ScheduleViewModel.kt
> +                        Log.d("scheTest", "실패")
앗 데이터 정보를 테스트 해본다고 적어놓고 제거를 까먹었네요!
수정하도록 하겠습니다

2024-02-24 16:41 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/ScheduleViewModel.kt
> +
뷰 모델이 복잡해서 코드가 복잡해지더라구요..🥲
최대한 간결하게 리펙토링 해보겠습니다

2024-02-24 16:42 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/cafeteria/CafeteriaFragment.kt
> +            stuKoreanMenuAdapter.submitList(it)
`student`의 약자인데 기존 코드를 그대로 적으면서 리팩토링을 생각 못 했네요
그리고 이 부분은 메뉴 브랜치의 코드가 섞여버린거 같습니다..🤔

2024-02-24 16:44 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/ScheduleFragment.kt
>                  .commit()
swagger로 테스트 해봤을때 해당 부분까지 가져오더라구요
이건 백엔드와 협의해보는 것이 좋을거 같습니당

2024-02-24 16:48 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/ScheduleViewModel.kt
> +                    }?.scheduleEntries.orEmpty()
저장 데이터가 없을 경우에는 `_scheduleList`에서 `postValue`로 데이터를 가공하고 저장 데이터가 있는 경우에는 `Gson` 데이터를 가공하는 경우라 필터링 부분이라 달라요!
`Collection` 함수를 사용하는 부분이라 공통 로직으로 묶을 수 있을지 확인 해봐야할거 같아용

2024-02-24 16:50 UTC, huiwoo-jo commented on app/src/main/res/layout/item_schedule.xml
>      </data>
뷰 바인딩으로 수정했는데 이 부분을 제거하는 것을 까먹었네요
수정하도록 하겠습니당

2024-02-25 02:30 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/adapter/ScheduleAdapter.kt
> +        fun bind(item: ScheduleEntry) {
`inner class`에 `fun bind`가 바로 있는 형태인데 `fun bind` 위에 개행을 원하시는건가요?

2024-02-25 06:17 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/adapter/ScheduleAdapter.kt
> +        fun bind(item: ScheduleEntry) {
넵 맞습니다

2024-02-26 03:45 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/adapter/ScheduleAdapter.kt
> +        fun bind(item: ScheduleEntry) {
다른 `Adapter` 모두 아래와 같은 형태라서 따로 개행은 필요 없을거 같은데 확인 부탁드려요~! 아래는 `NoticeAdapter`의 코드입니다

```
    inner class ViewHolder(private val binding: ItemNoticeBinding)
        : RecyclerView.ViewHolder(binding.root) {
            fun bind(item : Notice) {
                binding.notice = item
                binding.itemClickListener = itemClickListener
            }
    }
```

2024-02-26 04:07 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/cafeteria/CafeteriaFragment.kt
> +            stuKoreanMenuAdapter.submitList(it)
이 부분은 학식 관련 리펙토링 브랜치를 따로 만들어서 바꾸는게 좋을거 같습니다

2024-02-27 03:57 UTC, hoyahozz requested changes
코멘트 짧게 남겨보았습니다!

2024-02-27 03:57 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/data/remote/entity/Cafeteria.kt
> +    val menu: List<String>
```suggestion
    val menus: List<String>
```

가독성을 위해 컬렉션은 복수형태로 이름 지어주시면 좋을 것 같아요~

2024-02-27 03:57 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/data/remote/entity/Schedule.kt
> +    val date: List<String>
```suggestion
    val dates: List<String>
```

2024-02-27 03:57 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/data/remote/entity/Schedule.kt
> +    val yearSchedule: List<YearSchedule>,
```suggestion
    val yearSchedules: List<YearSchedule>,
```

2024-02-27 03:57 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/ScheduleViewModel.kt
> +                    }?.scheduleEntries.orEmpty()
```kotlin
fun getSchedulesForPickDate(list: List<Schedule>): List<ScheduleEntry> {
    return list
        .filter { schedule ->
            schedule.year == pickYear.value &&
                    schedule.yearSchedule.any { it.month == pickMonth.value }
        }.flatMap { schedule ->
            schedule.yearSchedule
                .find { it.month == pickMonth.value }
                ?.scheduleEntries.orEmpty()
        }
}
```

대략 이런식으로 분리할 수 있겠네요~
해당 함수가 하는 역할이 몇 개인지 생각해보면 무엇을 분리해야 할지 감이 오실거에요~

2024-02-27 13:38 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/adapter/ScheduleAdapter.kt
> +        fun bind(item: ScheduleEntry) {
```
    inner class ViewHolder(private val binding: ItemNoticeBinding)
        : RecyclerView.ViewHolder(binding.root) {
// 여기 함수 개행 해달라는 뜻이었습니당
            fun bind(item : Notice) {
                binding.notice = item
                binding.itemClickListener = itemClickListener
            }
    }
```

2024-02-28 02:18 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/adapter/ScheduleAdapter.kt
> +        fun bind(item: ScheduleEntry) {
확인했습니다!

2024-02-28 08:47 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/data/remote/entity/Cafeteria.kt
> +    val menu: List<String>
메뉴 관련 브랜치를 따로 제작하여 위에 `stu` 수정과 같이 수정하는게 좋을거 같습니다.

2024-02-28 08:57 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/ScheduleViewModel.kt
> +                    }?.scheduleEntries.orEmpty()
`Gson`으로 받아온 부분의 타입을 생각하지 못했네요 수정하도록 하겠습니다!

2024-02-29 00:32 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/schedule/ScheduleFragment.kt
>                  .commit()
백엔드 수정되는대로 변경하겠습니다

2024-03-13 12:27 UTC, m6z1 approved these changes
확인했습니다 고생했어용 머지 고고

2024-03-14 13:28 UTC, hoyahozz approved these changes

2024-03-15 11:52 UTC, merged