Feat : 웹 뷰 파일 다운로드 구현
TeamDMU/DMU-Android pull request #173
Opened 2024-02-25 06:24 UTC by m6z1

## 📮 관련 이슈
- resolved #169 

## ✍️ 구현 내용
- 웹 뷰에서의 첨부파일을 클릭했을 시 다운로드 받아지지 않던 이슈 해결했습니다.
- `DownloadListener` 자체를 지원해줘서 그 코드 사용했고, 코드 설명을 주석으로 달아놓았습니다.
- 머지되지 않은 브랜치를 사용해야 해서 rebase를 했더니 다른 브랜치의 기존 커밋 내역이 남아있습니다.

- ## 📷 구현 영상
[Screen_recording_20240225_152311.webm](https://github.com/TeamDMU/DMU-Android/assets/114990782/b67f1616-3fa5-4697-a7f6-201af2bdfdcb)

## ✔️ 확인 사항
- [ ] 컨벤션에 맞는 PR 타이틀
- [ ] 관련 이슈 연결
- [ ] PR 관련 정보 연결 (작업자, 라벨, 마일스톤 등)
- [ ] Github Action 통과

2024-02-28 02:58 UTC, hoyahozz requested changes

2024-02-28 02:58 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/detail/DetailActivity.kt
> +                    setTitle(URLUtil.guessFileName(url, contentDisposition, mimetype))
![image](https://github.com/TeamDMU/DMU-Android/assets/85336456/1779f6e8-01e8-4501-bf7e-4c70496a2971)

`URLDecoder` 를 활용하면 제목을 디코딩할 수 있습니다!

2024-02-28 02:58 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/detail/DetailActivity.kt
>              webViewClient = WebViewClient()
`initWebView` 로 한 번 더 함수 분리하는 것도 괜찮아보이네요~!

2024-03-13 15:47 UTC, huiwoo-jo approved these changes
실제 다운로드 확인을 위해서 `develop` 브랜치로 `rebase` 진행했습니다!
딱히 수정 할 사항은 없는거 같습니다 수고하셨어요👍

2024-03-13 15:56 UTC, hoyahozz approved these changes

2024-03-13 15:57 UTC, merged