Feat : 검색 기능 구현 (페이지네이션 제외)
TeamDMU/DMU-Android pull request #177
Opened 2024-03-02 13:58 UTC by m6z1

## 📮 관련 이슈
- resolved #174 

## ✍️ 구현 내용
- 추후 수정

## 📷 구현 영상
- 구현 영상을 업로드 해주세요.

## ✔️ 확인 사항
- [ ] 컨벤션에 맞는 PR 타이틀
- [ ] 관련 이슈 연결
- [ ] PR 관련 정보 연결 (작업자, 라벨, 마일스톤 등)
- [ ] Github Action 통과

2024-03-05 04:01 UTC, hoyahozz requested changes
코멘트 확인해주세요 :)

2024-03-05 04:01 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
> +            setHasFixedSize(true)
언제 사용할 수 있는 함수일까요?

2024-03-05 04:01 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
> +        }
`Done` 버튼은 어떤 상황에서 나타나나요? 좀 더 좋은 네이밍이 있지 않을까요?

2024-03-05 09:52 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchViewModel.kt
> +    val searchNotices: LiveData<List<Notice>?> = _searchNotices
eu 는 무엇이죠?

2024-03-05 09:59 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
> +        adapter = NoticeAdapter { url -> navigateToDetail(url) }
그럴 수 있겠네요. 한 번 수정해보겠습니다.

2024-03-05 10:27 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
> +            setHasFixedSize(true)
지금처럼 너비 혹은 높이가 `wrap_content`로 동적일 때 메서드에 `false`값을 넣어서 다시 뷰의 길이를 재야할 것 같습니다.
그런데 `requestLayout()` 메서드를 아이템이 변경될 때마다 호출하는 것은 고비용처리가 될 것 같은데, `0dp`혹은 `match_parent` 로 고정시켜놓고  `setHasFixedSize(true)`를 사용하는 게 더 좋겠죠 ?

2024-03-05 10:32 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
> +        }
`onSearchBtnClickListener()`으로 수정했는데 좀 더 직관적이고 좋은 네이밍이라고 생각합니다. 
검색 버튼을 눌렀을 때, 검색 로직이 실행되는 메서드이니 `search`라는 단어를 넣었습니다.

2024-03-05 10:56 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchViewModel.kt
> +    val searchNotices: LiveData<List<Notice>?> = _searchNotices
`null` 은 오류로 인해 값이 없는 경우인지 단순히 빈 리스트인지 구분하기도 어려울 뿐더러, 사용할 때마다 `null` 체크를 해주어야합니다. 그럼 코드 가독성이 많이 떨어지겠죠!

`emptyList` 는 읽는 사람 입장에서 컬렉션이 비어있다는 것이 명확히 인식이 되므로 가독성도 올라갑니다~ 이 부분은 혼자 더 공부를 해보시고 다시 답글 달아주시면 좋을 것 같아요

2024-03-05 10:57 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
> +            setHasFixedSize(true)
`0dp` 를 사용하면 뷰 길이가 고정되나요?

2024-03-05 10:57 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
> +        }
넵! 하지만 이전에도 말씀드렸다시피 `setOnEditorActionListener` 자체가 이미 함수로 분리되어 있기 때문에 한 번 더 나눠야 하는지는 조금 더 생각해보시면 좋을 것 같아요~

2024-03-06 09:23 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
> +            setHasFixedSize(true)
아 아뇨 ㅎ....ㅎ 내용에 따라 `wrap_content` 와 같은 역할을 합니다 고정되지 않아요. (...)

2024-03-08 13:48 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
> +        adapter = NoticeAdapter { url -> navigateToDetail(url) }
이 부분 어떻게 수정해야 할 지 감이 안 잡혀요 . . . .

2024-03-08 13:59 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchViewModel.kt
> +    val searchNotices: LiveData<List<Notice>?> = _searchNotices
`null safety`, 런타임 에러 방지 등이 있군요 ! 확실하게 코드 읽는 사람 입장에서도 `emptyList` 가 훨씬 나을 것 같네요

2024-03-09 07:41 UTC, hoyahozz commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
> +        adapter = NoticeAdapter { url -> navigateToDetail(url) }
단순하게 `named arguments` 를 사용해봐도 좋을 것 같습니다~

2024-03-09 12:56 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
> +        adapter = NoticeAdapter { url -> navigateToDetail(url) }
아하 반영해보겠습니다

2024-03-10 06:16 UTC, huiwoo-jo approved these changes
리뷰가 너무 늦었네요 죄송합니다🥲
수고하셨습니다👍

2024-03-10 06:16 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/data/repository/NoticeRepository.kt
> +                .getSearchNotice(searchWord, "컴퓨터소프트웨어공학과", page, DEFAULT_SIZE)
선택 학과 적용은 나중에 적용하시나요?

2024-03-10 06:16 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchViewModel.kt
> -class SearchViewModel : BaseViewModel() {
`BaseViewModel`을 상속 받지 않는 이유가 있나요?

2024-03-10 12:28 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/data/repository/NoticeRepository.kt
> +                .getSearchNotice(searchWord, "컴퓨터소프트웨어공학과", page, DEFAULT_SIZE)
넵 ~ 온보딩에서 룸에 저장한 이후에 적용 할 예정입니다

2024-03-10 12:30 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchViewModel.kt
> -class SearchViewModel : BaseViewModel() {
오잉 상속 받고 있어요! 오른쪽 코드 보심 될 것 같아유

2024-03-11 01:18 UTC, hoyahozz approved these changes
👍👍👍👍👍

2024-03-11 07:35 UTC, merged