Feat : 검색 화면 페이지네이션
TeamDMU/DMU-Android pull request #190
Opened 2024-03-14 02:31 UTC by m6z1

## 📮 관련 이슈
- resolved #178 

## ✍️ 구현 내용
- 검색 화면 무한스크롤 구현했습니다.

## 📷 구현 영상
- 구현 영상을 업로드 해주세요.

## ✔️ 확인 사항
- [ ] 컨벤션에 맞는 PR 타이틀
- [ ] 관련 이슈 연결
- [ ] PR 관련 정보 연결 (작업자, 라벨, 마일스톤 등)
- [ ] Github Action 통과

2024-03-14 12:19 UTC, huiwoo-jo requested changes
코멘트 확인 부탁드립니다!
수고하셨어요!!

2024-03-14 12:19 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
> +        setupInfinityScroll()
함수로 분리하지 않고 `initStartView`로 직접 넣으신 이유가 있을까요?

2024-03-14 12:19 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchViewModel.kt
> +                    _searchNotices.postValue(updatedResult)
`updatedReulst`보다 `updatedNotices`가 어떤 것이 updated 된 것인지 명확한거 같은데 `updatedResult`로 수정하신 이유가 있을까요?

2024-03-15 02:32 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchFragment.kt
> +        setupInfinityScroll()
따로 없습니다 ㅎ ㅎ 안그래도 지저분해보였는데 분리해야겠군요

2024-03-15 02:34 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/search/SearchViewModel.kt
> +                    _searchNotices.postValue(updatedResult)
`updatedNotices`는 '공지를 업데이트 한다' 라는 네이밍이고, 현재 뷰 에서는 `검색한 결과`에 대해서 다루는 것이니
`updatedNotices` 보다는 `updatedResult`로 수정했습니다. 그런데 어떤 결과인지를 모르니, `updatedSearchResult` 가 더 맞을 것 같군요

2024-03-15 11:54 UTC, huiwoo-jo approved these changes
수고많으셨습니다!

2024-03-16 12:15 UTC, merged