Feat : 알림 권한 설
TeamDMU/DMU-Android pull request #193
Opened 2024-03-20 22:51 UTC by huiwoo-jo

## 📮 관련 이슈
- resolved #189 

## ✍️ 구현 내용
- FCM을 위한 알림 권한 설정입니다.
- 스플래시 화면이 처음 켜질 경우 알림 권한을 요청합니다.
- 온보딩 화면 3단계에서 알림을 킬 경우 알림 권한을 거부한 상태일때, 설정 화면을 띄웁니다.
- 설정 화면을 띄우는 이유는 아래와 같습니다.
  - 어플에서는 사용자에게 2번을 초과하여 알림 설정을 요청할 수 없습니다.
  -  스위치 on/off 로직을 위하여 설정 화면으로 이동합니다.
- 수정 필요
  원활한 개발을 위하여 우선 스플래시와 온보딩만 구현을 하였으나 아래와 같은 수정이 필요합니다.
  - 설정 화면으로 이동하기 전 다이어그램을 띄워 사용자에게 전달하도록 수정할 필요가 있습니다.
  - 어플 세팅 화면에서 알림을 킬 때 똑같은 로직이 필요하며, 수정이 필요합니다.

## 📷 구현 영상
- 영상은 다시 올리겠습니다.

## ✔️ 확인 사항
- [x] 컨벤션에 맞는 PR 타이틀
- [x] 관련 이슈 연결
- [x] PR 관련 정보 연결 (작업자, 라벨, 마일스톤 등)
- [ ] Github Action 통과

2024-03-22 00:28 UTC, m6z1 requested changes
코멘트 확인 한 번만 부탁드립니다!!! 고생하셨어용

2024-03-22 00:28 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/permission/OnboardingPermissionActivity.kt
> +                setPermissionSwitch(false)
온보딩 알림 스위치를 활성화 시키는데 boolean 값을 `false` 로 받나요 ?

2024-03-22 00:28 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/splash/SplashActivity.kt
> +                        this@SplashActivity, arrayOf(Manifest.permission.POST_NOTIFICATIONS), 100
뒤에 100은 무슨 수인가요?

2024-03-22 00:28 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/splash/SplashActivity.kt
> +    ) {
```suggestion
        requestCode: Int,
        permissions: Array<String>,
        grantResults: IntArray
    ) {
```

줄바꿈이 있으면 더욱 가독성이 좋아질 것 같아요!

2024-03-22 00:28 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/splash/SplashActivity.kt
> +                Intent(this@SplashActivity, MainActivity::class.java)
지금 각 뷰마다 동일한 액티비티로 넘어가는 `intent`가 많은데, 넘어가야 할 각 뷰에서 intent객체를 미리 만들어놓고 사용하는 방법도 제가 배워왔습니다!!!

예를 들어서, 지금 `OnboardingDepartActivity`로 넘어가야 하는 경우에는

> `OnboardingDepartActivity` 에서
``` kotlin
companion object {
   fun createIntent(context: Context): Intent {
      return Intent(context, OnboardingDepartActivity::class.java)
   }
} 
```
로 객체를 만들고,

현 액티비티에서
```
val intent = OnboardingDepartActivity.createIntent(this@SplashActivity)
```
로 사용할 수도 있습니다!

이렇게 사용하면 캡슐화 할 수 있다는 큰 장점이 있다고 합니다 ( _ _

2024-03-22 01:36 UTC, huiwoo-jo reviewed
코멘트 남겨주셔서 감사합니다
권한 요청 코드 부분에 대하여 확인해주시면 감사하겠습니다

2024-03-22 01:36 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/permission/OnboardingPermissionActivity.kt
> +                setPermissionSwitch(false)
기본 설정을 위하여 `false`로 처리합니다
권한 설정이 미허용일 때는 `false`로 설정하기 위해서 기본 값을 `false`로 한 뒤 권한 설정 부에서 바꿉니다!
주석 처리로 설명을 붙히거나 코드를 깔끔하게 수정해보도록 하겠습니다

2024-03-22 01:36 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/splash/SplashActivity.kt
> +    ) {
변경하겠습니다!

2024-03-22 01:36 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/splash/SplashActivity.kt
> +                Intent(this@SplashActivity, MainActivity::class.java)
새로운 것을 배워갑니다.. 👍 
맞춰서 수정해보겠습니다

2024-03-22 01:36 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/splash/SplashActivity.kt
> +                        this@SplashActivity, arrayOf(Manifest.permission.POST_NOTIFICATIONS), 100
권한 요청 코드입니다!
권한이 거부 되었을 경우 요청코드를 확인하며 사용자가 지정합니다!
`unique`한 값으로 지정해야하는데 100을 그냥 넣으니 무슨 숫자인지 어렵긴하네요
상수 `REQUEST_PERMISSION_CODE`로 수정해보겠습니다

2024-03-22 01:36 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/splash/SplashActivity.kt
> +                        this@SplashActivity, arrayOf(Manifest.permission.POST_NOTIFICATIONS), 100
해당 코드에서는 거부했을 경우 권한 요청 코드를 다시 받아서 처리하는 부분이 없어 재사용하지 않는 값이라 상수로 빼는게 맞을지 고민이긴합니다..

2024-03-22 01:40 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/permission/OnboardingPermissionActivity.kt
> +                setPermissionSwitch(false)
```
override fun initStartView() {
        viewModel.checkAccessAlarm()
        viewModel.getUserDepartment()
        setPermissionSwitch(false)
```

여기서 기본 설정으로 `false`값을 지정해주었는데 또 기본 설정을 해주어야 하는 걸까요 ?

2024-03-22 01:41 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/splash/SplashActivity.kt
> +                        this@SplashActivity, arrayOf(Manifest.permission.POST_NOTIFICATIONS), 100
재사용하지 않더라도 상수화 해주면 되지 않을까요?

```
companion object {
   private const val REQUEST_PERMISSION_CODE = 100
```

2024-03-22 01:44 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/splash/SplashActivity.kt
> +                        this@SplashActivity, arrayOf(Manifest.permission.POST_NOTIFICATIONS), 100
앗 지금 생각하니 72번줄에 권한 요청 코드를 받는 부분이 있네요
다른 뷰에서도 계속 재사용할듯하니 상수화 하도록 하겠습니다

2024-03-22 01:46 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/permission/OnboardingPermissionActivity.kt
> +                setPermissionSwitch(false)
스위치값이 설정 여부와 상관없이 `isChecked`가 활성화됩니다
`isChecked`만 따로 설정을 다시 하는게 나을까요?

2024-03-22 01:48 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/splash/SplashActivity.kt
> +                        this@SplashActivity, arrayOf(Manifest.permission.POST_NOTIFICATIONS), 100
제가 궁금했던 부분은 꼭 다른 뷰에서도 이 값을 사용해야 하기에 상수화를 한다고 생각하시는 지가 궁금했어요!
위에 예시코드처럼`private` 으로 접근지정자를 선언해주면 클래스 내부에서만 사용할 수 있습니다!!

2024-03-22 01:57 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/permission/OnboardingPermissionActivity.kt
> +                setPermissionSwitch(false)
오호 이해했습니다. 스위치 버튼을 누를 경우 `isChecked` 가 활성화되면서 버튼이 활성화 되어서 `setPermissionSwitch(false)`를 주신 거 맞을까요 ?

2024-03-22 02:06 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/permission/OnboardingPermissionActivity.kt
> +                setPermissionSwitch(false)
네 맞습니다!
`setPermissionSwitch(false)`로 함수 호출 하는 것보다 `binding.switchPermission.isChecked = false`로 처리하는게 나을지 고민입니다

2024-03-22 02:07 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/splash/SplashActivity.kt
> +                        this@SplashActivity, arrayOf(Manifest.permission.POST_NOTIFICATIONS), 100
아 그 뜻이었군요! 다른 의미로 생각했네요
알림 권한 거부에 대한 권한 요청 코드는 세팅에서도 사용해야하니 상수화하는게 맞을거 같습니다!!

2024-03-22 02:18 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/permission/OnboardingPermissionActivity.kt
> +                setPermissionSwitch(false)
버튼이 활성화되면서 바뀌는 로직이 색상 변경밖에 없다면, `binding.switchPermission.isChecked = false`로 처리해도 될 것 같긴 한데, 다른 로직은 포함되어있지 않은지 확인 한 번 해보시면 좋을 것 같아요!

2024-03-22 02:20 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/permission/OnboardingPermissionActivity.kt
> +                setPermissionSwitch(false)
버튼이 켜지는 것만 영향을 줘서 `binding.switchPermission.isChecked = false`으로 수정해도 충분할거 같습니다!
수정 후 테스트 해보면서 영향 주는 로직이 있는지 확인해보겠습니다

2024-03-23 22:17 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/splash/SplashActivity.kt
> +                        this@SplashActivity, arrayOf(Manifest.permission.POST_NOTIFICATIONS), 100
세팅 화면에서의 권한 요청을 페이지 이동으로 변경되었기에 `REQUEST_PERMISSION_CODE`가 아닌 
`PackageManager.PERMISSION_GRANTED == ContextCompat.checkSelfPermission(
                        this, Manifest.permission.POST_NOTIFICATIONS
                    )`로 가능할거 같습니다!
`Spalsh.kt`의 `companion object`부에 선언하였습니다

2024-03-24 11:57 UTC, m6z1 approved these changes
굿굿 tv 👍

2024-03-25 08:10 UTC, merged