Feat : 설정화면 fcm 토큰 관련 api 연동
TeamDMU/DMU-Android pull request #216
Opened 2024-03-30 11:09 UTC by m6z1

## 📮 관련 이슈
- resolved #175 

## ✍️ 구현 내용
- 스위치 알림 버튼 on/off가 api 구현에 따른 로직에 의해 반영되도록 수정했습니다.
- 학과 / 대학 공지 알림 off 시 delete api 연결했습니다.
- 학과 / 대학 공지 알림 on 시 update api 연결했습니다.
- 설정화면에서 학과 수정 시 메인으로 이동하는 로직을 `finish()`처리만 해서 다시 설정화면으로 돌아오도록 수정했습니다.
- 설정화면에서 키워드 액티비티 진입 후 완료 버튼 눌렀을 때 키워드 api 가 통신되도록 구현했습니다.

## 📷 구현 영상
<img width="840" alt="스크린샷 2024-03-30 오후 8 09 26" src="https://github.com/TeamDMU/DMU-Android/assets/114990782/7a32012d-d5a9-4ad2-a3f5-ca78306e5ccc">
서버 통신 200 로그로 구현 영상 대체합니다

## ✔️ 확인 사항
- [ ] 컨벤션에 맞는 PR 타이틀
- [ ] 관련 이슈 연결
- [ ] PR 관련 정보 연결 (작업자, 라벨, 마일스톤 등)
- [ ] Github Action 통과

2024-03-30 12:19 UTC, huiwoo-jo requested changes
수고많으셨습니다!
코멘트 확인 부탁드려요 👍

2024-03-30 12:19 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/service/FCMService.kt
> +        SharedPreference.setFcmToken(token)
`Timber`은 지워도 될거 같아용

2024-03-30 12:19 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/standard/network/RetrofitObject.kt
네트워크 시간 때문에 늘린건가요?

2024-03-30 12:19 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartActivity.kt
>              finish()
메인 화면으로 이동하는 부분은 일부러 지우신건가요?

2024-03-30 12:19 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/keyword/KeywordActivity.kt
> -            }
👍

2024-03-30 12:19 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/main/MainActivity.kt
>          })
여기도 이제 `Timber`은 지워도 될거같아요!

2024-03-30 12:19 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/SettingFragment.kt
>      }
첫 줄 함수 개행으로 컨벤션 확정인가요?
전에 같은 이슈가 나왔었는데 확실하게 정하지 못했던거 같아서 여쭤봅니다!

2024-03-30 12:19 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/SettingFragment.kt
> +
`it`을 명시할때 `department`, `myTopics`라 약간 혼동이 옵니다
통일을 하는게 좋을거 같아요

2024-03-30 12:19 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/SettingViewModel.kt
> +            when (val result = settingRepository.updateUserDepartment(
개인적으로 코드가 `viewModelScope.launch`처럼 길어질 때 코드 사이에 공백이 있는게 보기 편하더라구요!
효율적인 부분에서는 잘 모르겠어서 의견 말해주시면 컨벤션을 맞추는게 좋을거 같습니다

2024-03-30 12:19 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/SettingViewModel.kt
사용하지 않는 호출은 지워주세요 👍

2024-03-30 12:36 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/standard/network/RetrofitObject.kt
넵 키워드 때문에 타임 아웃 에러나서 서버 측에서 로직 수정해주시면 다시 10으로 되돌릴 예정입니당

2024-03-30 12:36 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/DepartActivity.kt
>              finish()
네 이 부분 사용해보셨는지 모르겠는데 불편하기도 하고, 학과가 바꼈는지 확인이 안 되기에 finish처리만 했습니다.

2024-03-30 12:37 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/SettingFragment.kt
>      }
넴 고고 합시다

2024-03-30 12:37 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/setting/SettingViewModel.kt
> +            when (val result = settingRepository.updateUserDepartment(
공백도 컨벤션이라고 했는데 공백 추가하는 걸로 맞추겠슴다

2024-03-31 13:28 UTC, huiwoo-jo approved these changes
수고하셨습니다! 👍

2024-03-31 13:29 UTC, merged