Feat : 최초 어플 실행 작업 및 토큰 등록
TeamDMU/DMU-Android pull request #217
Opened 2024-03-30 12:25 UTC by huiwoo-jo

## 📮 관련 이슈
- resolved #213 

## ✍️ 구현 내용
- 화면 최초 실행 완료 부분을 `firstLaunch`부를 `onboardingKeyword`에서 `MainActivity`로 수정하였습니다.
- 온보딩 매과정에서 확인하던 `firstLaunch`를 제거하였습니다.
- `onboardingPermission`의 알림 권한 승인의 버전 확인을 수정하였습니다.
- `MainActivity`에 최초 접근 시 토큰, 학과, 키워드(토픽)을 등록하는 api를 연결하였습니다.
- ⭐ 내용 수정중

## 📷 구현 영상
- 구현 영상을 업로드 해주세요.

## ✔️ 확인 사항
- [ ] 컨벤션에 맞는 PR 타이틀
- [ ] 관련 이슈 연결
- [ ] PR 관련 정보 연결 (작업자, 라벨, 마일스톤 등)
- [ ] Github Action 통과

2024-03-31 12:30 UTC, m6z1 requested changes
코멘트 확인 부탁드려용 고생많으ㅅ셨습니당

2024-03-31 12:30 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/main/MainActivity.kt
> -    }
요 코드 필요한데 왜 지우신 거져 ?! 제 피알에 있어서 지우신건가욤

2024-03-31 12:30 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/main/MainViewModel.kt
> +    fun issuedToken() {
`issuedToken` 네이밍이 애매한 것 같아요! 그리고 이 로직은 MainActivity에 있었는데,  제 피알 보시면 메인 액티비티에서 sharedPreferences에 저장하고 있어서 이 로직은 추가하지 않고 레포지토리에서 prefs 가져오는 메서드로 fcmtoken을 받아오는 게 맞을 것 같습니다.

2024-03-31 12:30 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/main/MainViewModel.kt
> +            _myTopics.value = keyword
한 메서드에 여러 가지 내용이 담겨있는 것 같아요, department 를 가져오는 로직과, keyword 를 가져오는 로직은 분리 하는 게 어떨까요 ??

2024-03-31 12:30 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/main/MainViewModel.kt
> +            _myTopics.value = keyword
그리고 `_myDepartment.postValue(department)` 와 `_myDeparment.value = department` 는 어떤 차이가 있는 것인지도 궁금해요! 섞어서 쓰셨길래 이유가 있는지 여쭙고 싶습니당

2024-03-31 12:30 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/main/MainViewModel.kt
> +            when (val result = mainRepository.setUserToken(token)) {
```suggestion
            when (val result = mainRepository.setUserToken(
            Token(
                token = FCMToken.value.toString(),
                department = myDepartment.value ?: "",
                topics = myTopics.value ?: emptyList()) {
```
요 코드는 어떻게 생각하시는지두 궁금해여!

2024-03-31 12:30 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/splash/SplashActivity.kt
> +    private lateinit var intent: Intent
`intent` 를 지연초기화로 두신 이유가 있나용 ?
밑에서 `val intent = `로 다시 변수를 만드는 것 같아요

2024-03-31 12:30 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/splash/SplashActivity.kt
> +            intent = OnboardingDepartActivity.createIntent(this@SplashActivity)
아 중복되는 intent라서 그런 것 같네요, 그렇다면 혹시 
```
private val intent = OnboardingDepartActivity.createIntent(this@SplashActivity)
```
으로 선언해두고 startActivity(intent)로 사용하는 건 어떤지도 궁금해여

2024-03-31 14:26 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/depart/OnboardingDepartActivity.kt
> +                Unit
자동 정렬이 자꾸 Unit을 줄바꿈을 하더라구요🥲
자동 정렬 후 수정하는데 확인을 못하고 올렸나봅니다

2024-03-31 14:29 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/main/MainActivity.kt
> -    }
`viewModel`의 `issuedToken`으로 들어갔습니담

2024-03-31 14:31 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/main/MainViewModel.kt
> +    fun issuedToken() {
음 `MainActivity`로 다시 바꾼 뒤에 코드를 수정해보도록 하겠습니다

2024-03-31 14:33 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/main/MainViewModel.kt
> +            _myTopics.value = keyword
분리된 상태로 진행을 하니 department, keyword, token 동작하지 않고 중도 종료 되어서 이렇게 수정하였습니다
로직을 다 확인하지 못하여 통신이 되지 않아 어쩔 수 없이 하나의 로직에 넣었습니다
제 생각에는 `viewModeScope.launch`가 동시에 불려오면서 제대로 적용되지 않는거 같습니다

2024-03-31 14:33 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/main/MainViewModel.kt
> +            _myTopics.value = keyword
`_myDepartment.postValue(department)`로 통일되는게 맞습니다! 수정하도록 하겠습니다

2024-03-31 14:35 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/main/MainViewModel.kt
> +            when (val result = mainRepository.setUserToken(token)) {
`toekn`값이 들어가기 전 로직을 확인하기에는 기존 코드가 더 낫다고 판단하여 넣었지만 확인이 편리하다는 점 외에는 쓸데가 없어서 이게 더 나을거 같네요 수정하도록 하겠습니다

2024-03-31 14:36 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/splash/SplashActivity.kt
> +            intent = OnboardingDepartActivity.createIntent(this@SplashActivity)
이렇게 진행했었는데 최초 실행 이후에 어플을 실행하면 외인지 어플 실행이 안된더라구요..
다른 코드가 문제였을 수 있으니 다시 수정해서 한 번 확인해보도록 하겠습니다

2024-03-31 14:36 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/splash/SplashActivity.kt
> +    private lateinit var intent: Intent
`intent` 값을 지정하니 아래 코멘트와 같은 문제가 발생하였습니다

2024-03-31 16:14 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/main/MainViewModel.kt
> +            _myTopics.value = keyword
전에 관련된 리뷰를 통해서 공부했던 내용인데.. 제가 잘못 알고 있는 부분이 있을 수 있습니다
관련 코멘트를 남겨놓을테니 참고 부탁드려요! https://github.com/TeamDMU/DMU-Android/pull/158#discussion_r1499182875

2024-03-31 16:28 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/main/MainViewModel.kt
> +            _myTopics.value = keyword
앗 `postValue` 설정을 잘못해서 발생한 이슈였습니다 😢

2024-04-01 06:55 UTC, m6z1 approved these changes
LGTM

2024-04-01 06:55 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/splash/SplashActivity.kt
> +            intent = MainActivity.createIntent(this@SplashActivity)
오 요 부분 성공했나요 ? 저도 몰라서 질문한 거였는데

2024-04-01 06:55 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/main/MainViewModel.kt
> +            _myTopics.value = keyword
그렇다면 `department`는 데이터가 즉시 반영되지 않아도 되는 것일까요?

2024-04-01 07:36 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/main/MainViewModel.kt
> +            _myTopics.value = keyword
`_myDepartment.value`가 백에드에서 처리되면 `initToken`을 반영하기 전에 데이터가 올라가지 않을 수 있습니다!
그래서 `_myDepartment.value = department`로 학과가 온전히 저장되어야 하기 때문에 `postValue`가 아닌 `=`을 사용하여야합니다!

2024-04-01 07:36 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/splash/SplashActivity.kt
> +            intent = MainActivity.createIntent(this@SplashActivity)
성공했습니다 😄

2024-04-01 07:40 UTC, m6z1 commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/main/MainViewModel.kt
> +            _myTopics.value = keyword
넹 그런데 코드에선 postValue로 department를 업데이트하길래 물어봤어염
<img width="454" alt="스크린샷 2024-04-01 오후 4 39 56" src="https://github.com/TeamDMU/DMU-Android/assets/114990782/55722163-71ab-4c86-9e3d-89c4dc3e51a2">

2024-04-01 07:46 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/main/MainViewModel.kt
> +            _myTopics.value = keyword
오잉 아래 코드처럼 함수 분리까지 적용하여 수정 후 푸쉬까지 했는데 여기서 적용이 안된걸로 보이네요...? github에 적용된걸 확인 후 머지하겠습니다!

```
    fun setFCMToken(token: String){
        mainRepository.setFCMToken(token)
        _FCMToken.postValue(token)
    }

    private fun getUserDepart(){
        _myDepartment.value = mainRepository.getUserDepartment()
    }

    private fun getUserTopic(){
        viewModelScope.launch {
            _myTopics.value = mainRepository.getUserTopic()
        }
    }

    fun setInitToken() {
        _isLoading.postValue(true)

        viewModelScope.launch {
            when (val result = mainRepository.setUserToken(Token(
                token = FCMToken.value.toString(),
                department = myDepartment.value ?: "",
                topics = myTopics.value ?: emptyList()
            )
            )) {
                is NetworkResult.Success -> {
                    mainRepository.setIsFirstLaunch(false)
                    _isFirstLaunch.postValue(false)
                    _isLoading.postValue(false)
                    _isError.postValue(false)
                }
```

2024-04-01 08:04 UTC, huiwoo-jo commented on app/src/main/java/com/dongyang/android/youdongknowme/ui/view/main/MainViewModel.kt
> +            _myTopics.value = keyword
리베이스하니 잘 뜨네요!
확인 부탁드려용

2024-04-01 08:07 UTC, merged